CREATE TABLE IF NOT EXISTS STUDENT (
    ID BIGSERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR(20) NOT NULL,
    LAST_NAME VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    CONSTRAINT email_unique UNIQUE (email)
    );

CREATE TABLE IF NOT EXISTS COURSE (
    ID BIGSERIAL PRIMARY KEY,
    COURSE_NAME VARCHAR(35) NOT NULL
    );

CREATE TABLE courses_students (
    course_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    PRIMARY KEY (course_id, student_id),
    FOREIGN KEY (course_id) REFERENCES COURSE (ID) ON DELETE CASCADE,
    FOREIGN KEY (student_id) REFERENCES STUDENT (ID) ON DELETE CASCADE
);